codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: 70..100
  status:
    project:
      default:
        target: 85%
        threshold: 2%
        if_no_uploads: success
        if_not_found: success
    patch:
      default:
        target: 85%
        threshold: 0%
        if_no_uploads: success
        if_not_found: success

ignore:
  - "tests/**"
  - "docs/**"
  - "examples/**"
  - "htmlcov/**"
  - "algorithms/**/tests/**"

comment:
  layout: "reach, diff, flags, files"
  require_changes: false
  require_base: false
  require_head: false
  behavior: default
