services:
  cspbench-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - NCBI_EMAIL=${NCBI_EMAIL:-user@example.com}
      - NCBI_API_KEY=${NCBI_API_KEY:-your_key_here}
    volumes:
      - ./datasets:/app/datasets:ro
      - ./config:/app/config:ro
      - ./outputs:/app/outputs
      - /tmp:/app/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching and async tasks
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
