# CSPBench Cloud Run Configuration
# Generic configuration for multiple cloud providers

runtime: custom
env: flex

# Automatic scaling configuration
automatic_scaling:
  min_num_instances: 0
  max_num_instances: 10
  cool_down_period_sec: 60s
  cpu_utilization:
    target_utilization: 0.6

# Resource allocation
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Network configuration
network:
  session_affinity: false
  forwarded_ports:
    - 8000

# Environment variables
env_variables:
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  PORT: "8000"
  HOST: "0.0.0.0"
  WORKERS: "1"

# Health check configuration
liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
