# Cloud production settings - Google Cloud Run optimized
infrastructure:
  dataset_repository:
    implementation: "FileDatasetRepository"
    config:
      base_path: "/app/datasets/"  # Internal container path
      
  session_manager:
    implementation: "SessionManager"
    config:
      base_path: "/app/tmp/sessions/"  # Internal temp directory
      max_session_age_minutes: 30     # Shorter for cloud
      cleanup_interval_minutes: 5     # More frequent cleanup
      
  logging:
    level: "INFO"
    file_path: "/app/logs/cspbench.log"
    
# Web interface specific settings
web:
  host: "0.0.0.0"
  port: 8000  # Will be overridden by Cloud Run PORT env var
  debug: false
  max_request_size_mb: 10
  session_timeout_minutes: 30
  
# Cloud-specific optimizations  
cloud:
  environment: "production"
  enable_cors: true
  allowed_origins: ["*"]  # Configure properly for production
  max_concurrent_executions: 5
  execution_timeout_seconds: 300
  
# Algorithm defaults for cloud
algorithms:
  default_timeout: 120
  max_memory_mb: 512
  enable_progress_tracking: true
