# Cloud Run Configuration Template
# This file ensures consistent resource allocation for Cloud Code deploys
# CRITICAL: These settings override Cloud Code defaults to prevent 256Mi memory limit

service:
  name: csp-bench
  region: us-central1
  platform: managed
  
resources:
  memory: 2Gi              # CRITICAL: Must be 2Gi, NOT 256Mi
  cpu: 1000m               # CRITICAL: 1 full CPU
  timeout: 900s            # CRITICAL: Extended timeout for startup
  concurrency: 80
  max_instances: 10
  min_instances: 0

port: 8080

environment:
  PORT: "8080"
  PYTHONPATH: "/app"
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"

security:
  allow_unauthenticated: true
  
startup:
  # Give enough time for Python application to start
  startup_timeout: 900s
  # TCP probe for port 8080
  startup_probe:
    tcp_socket:
      port: 8080
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    failure_threshold: 10
