"""
Default configurations for CSC algorithm.

Attributes:
    CSC_DEFAULTS (dict): Default CSC parameters.
"""

# CSC Configuration
CSC_DEFAULTS = {
    "min_d": 2,
    "d_factor": 0.8,
    "min_blocks": 2,
    "max_blocks": 4,
    "n_div": 6,
    "l_div": 25,
    # New parameters for control and performance
    "max_candidates": 5000,  # Limit of candidates generated by recombination
    "local_search_max_iterations": 50,  # Max iterations for local search
    "candidate_eval_batch": 200,  # Batch size for progress updates during evaluation
}
